# Generated by Django 2.2.4 on 2019-08-10 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apostila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('apostila', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.Apostila')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.Aula')),
            ],
            options={
                'ordering': ('ordem',),
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='apostilas',
            field=models.ManyToManyField(blank=True, related_name='aulas', through='cursos.Pacote', to='cursos.Apostila'),
        ),
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.Curso'),
        ),
    ]
