# Generated by Django 2.2.4 on 2019-08-10 16:26

from django.db import migrations, models
import django.db.models.deletion
import sort_order_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apostila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0, verbose_name='Sort')),
                ('label', models.CharField(max_length=100)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Poll')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', sort_order_field.fields.SortOrderField(db_index=True, default=0, verbose_name='Sort')),
                ('apostila', models.ForeignKey(on_delete=None, to='cursos.Apostila')),
                ('aula', models.ForeignKey(on_delete=None, to='cursos.Aula')),
            ],
            options={
                'ordering': ('ordem',),
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='apostilas',
            field=models.ManyToManyField(blank=True, related_name='aulas', through='cursos.Pacote', to='cursos.Apostila'),
        ),
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='cursos.Curso'),
        ),
    ]
