# Generated by Django 2.2.4 on 2019-08-23 02:51

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
	TrigramExtension(),
        migrations.AlterModelOptions(
            name='pacote',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterField(
            model_name='apostila',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='apostila',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='apostila',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(upload_to='static/images/cursos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
    ]
